# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-23 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ins_Item', models.CharField(max_length=100, verbose_name='巡检项')),
                ('resource_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.SystemInfo', verbose_name='所属业务系统')),
            ],
            options={
                'verbose_name_plural': '新媒体巡检项目',
                'verbose_name': '新媒体巡检项目',
            },
        ),
        migrations.CreateModel(
            name='usercheckNewMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='巡检人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='巡检时间')),
                ('service', models.IntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='巡检项状态')),
                ('details', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('insitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.NewMedia', verbose_name='巡检项')),
            ],
            options={
                'verbose_name_plural': '新媒体巡检记录',
                'verbose_name': '新媒体巡检记录',
                'ordering': ['-add_time'],
            },
        ),
    ]
